### ISSUE TITLE
Chair onboarding checklist: Cheuk

### ISSUE THREAD

**Issue by sleepypioneer** [psf/community-code-of-conduct#15]
- [ x ] invite new member to the group meetings (google calendar)
- [ ] Give access to the relevant documents listed below
  - [x] [Meeting Notes, Agenda, and Action Items](https://docs.google.com/document/d/1mbwEbRZfk5CaPedMF2kjKlhTxH8YhpsBzR2rCO3jsE8/edit?usp=sharing)
  - [ ] [PSF Conduct Work Group Email Templates](https://docs.google.com/document/d/1XFESSvl_OtYeixH4ObxaynA5gFeOoGe6URMGbGldv2A/edit?ts=60ef64f2)
  - [ ] [Groups The PSF Advises](https://docs.google.com/spreadsheets/d/1q-4wbfCzrOPyZqjaoXqO1gBs54j8b0r5xdCSQPIXaWE/edit?ts=604959e6#gid=0)
  - [ ] [Conduct WG Reports Log](https://docs.google.com/spreadsheets/d/1SkpFnhod6vA0jq8HNkuZxWjFJH8U49t-FyKz_lNS9Rs/edit#gid=623564323)
  - [ ] [Code of Conduct Member Application Form (Responses)](https://docs.google.com/spreadsheets/d/1zQJt7W4pqI7TjdoNs9_-ULJ7PRzwyu-MVvCgscfx6ig/edit?usp=sharing)
